Hide CDE history button on unsaved dynamic forms
When a user clicked on the "View previous values" button on the forms of
a new angelman patient, nothing happened.

The following exception occurred:
AttributeError: 'NoneType' object has no attribute 'get'

Since the forms are not yet saved, there's no need to show the button.